#!/usr/bin/env python
"""Generate the Phase-1 report's result tables and number macros from the pipeline output.

The report must not carry hand-copied numbers (workspace rule ``C-0009``): every figure in the
tables and in the prose comes from the JSON/CSV artefacts the pipeline wrote, so re-running the
pipeline and this script keeps the report consistent.

Writes LaTeX fragments into ``docs/phase1-report/tables/``:

- ``results-<key>.tex``  full ``table`` environment, model ranking
- ``baseline.tex``       forecast vs uncontrolled baseline over the primary window
- ``keynumbers.tex``     ``\\newcommand`` macros for numbers quoted in prose

Usage
-----
    python subprojects/sp1-data-forecasting/scripts/make_report_tables.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

SRC_DIR = Path(__file__).resolve().parents[1] / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from sp1.config import repo_root, sp1_settings

#: Dataset key -> (display label, table label, caption noun phrase)
DATASETS = {
    "boulder": ("Boulder (primary)", "tab:res-boulder", "Out-of-sample accuracy on the primary site."),
    "palo-alto": ("Palo Alto (validation)", "tab:res-paloalto", "Out-of-sample accuracy on the validation site."),
}

#: Model ids would break LaTeX because of their underscores.
MODEL_LABELS = {
    "gradient_boosting": "gradient boosting",
    "xgboost": "XGBoost",
    "random_forest": "random forest",
    "ridge": "ridge regression",
    "hour_of_week_profile": "hour-of-week profile",
    "naive_daily": "naive daily",
    "naive_weekly": "naive weekly",
}


def load_json(path: Path) -> dict:
    """Read a JSON artefact, tolerating the UTF-8 BOM PowerShell redirection adds."""
    return json.loads(path.read_text(encoding="utf-8-sig"))


def fmt(value: float, digits: int = 4) -> str:
    """Format a metric; keep the sign so the negative R² stays visible."""
    return f"{value:,.{digits}f}" if value >= 0 else f"$-{abs(value):,.{digits}f}$"


def results_table(key: str, interim: Path) -> tuple[str, dict]:
    """Return the LaTeX ``table`` environment for one dataset and its key numbers."""
    label, table_label, caption = DATASETS[key]
    ranking = pd.DataFrame(load_json(interim / f"metrics-us-{key}.json")["ranking"])
    ranking = ranking.sort_values("wape").reset_index(drop=True)
    run = load_json(interim / f"run-us-{key}.json")
    best = ranking.iloc[0]

    rows = []
    for _, row in ranking.iterrows():
        name = MODEL_LABELS.get(row["model"], row["model"].replace("_", r"\_"))
        if row["model"] == best["model"]:
            rows.append(
                f"\\textbf{{{name}}} & \\textbf{{{row['wape']:.4f}}} & {fmt(row['mae_kwh'], 2)} "
                f"& {fmt(row['rmse_kwh'], 2)} & {fmt(row['r2'], 3)} \\\\"
            )
        else:
            rows.append(
                f"{name} & {row['wape']:.4f} & {fmt(row['mae_kwh'], 2)} "
                f"& {fmt(row['rmse_kwh'], 2)} & {fmt(row['r2'], 3)} \\\\"
            )

    origins = int(run["evaluation"]["n_origins"])
    body = "\n".join(rows)
    tex = f"""% generated by scripts/make_report_tables.py -- do not edit by hand
\\begin{{table}}[H]
\\centering
\\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\\toprule
Model & WAPE & MAE (kWh/h) & RMSE (kWh/h) & $R^2$ \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\caption{{{label}: {caption} {origins} daily origins, {origins * 24} out-of-sample intervals, all models retrained per origin.}}
\\label{{{table_label}}}
\\end{{table}}
"""
    numbers = {
        "origins": origins,
        "intervals": origins * 24,
        "best_model": MODEL_LABELS.get(best["model"], best["model"]),
        "best_wape": float(best["wape"]),
        "best_r2": float(best["r2"]),
        "naive_daily_wape": float(ranking.loc[ranking["model"] == "naive_daily", "wape"].iloc[0]),
    }
    numbers["improvement_pct"] = 100 * (1 - numbers["best_wape"] / numbers["naive_daily_wape"])
    return tex, numbers


def pattern_numbers(key: str, interim: Path) -> dict:
    """Peak/trough hours and energy totals from the pattern summary."""
    payload = load_json(interim / f"patterns-us-{key}.json")
    rows = sorted(payload["by_local_hour"], key=lambda r: -r["share_of_energy"])
    return {
        "total_gwh": payload["total_energy_kwh"] / 1e6,
        "peak_hour": int(rows[0]["local_hour"]),
        "peak_share_pct": rows[0]["share_of_energy"] * 100,
        "trough_hour": int(rows[-1]["local_hour"]),
        "trough_share_pct": rows[-1]["share_of_energy"] * 100,
        "peak_to_trough": rows[0]["mean_kwh"] / rows[-1]["mean_kwh"],
    }


def baseline_table(interim: Path, processed: Path) -> tuple[str, dict]:
    """Return the forecast-versus-baseline table for the primary window."""
    backtest = pd.read_csv(interim / "backtest-us-boulder.csv", parse_dates=["timestamp"])
    baseline = pd.read_csv(processed / "sp1-baseline-demand-v1.csv")

    actual = backtest["actual_kwh"]
    predicted = backtest["predicted_demand_kwh"]
    lower, upper = backtest["lower_bound_kwh"], backtest["upper_bound_kwh"]
    coverage = float(((actual >= lower) & (actual <= upper)).mean() * 100)
    amplification = float(baseline["predicted_demand_kwh"].max() / predicted.max())
    conserved = float(baseline["predicted_demand_kwh"].sum() / actual.sum() - 1)
    bias = float(predicted.sum() / actual.sum() - 1)

    tex = f"""% generated by scripts/make_report_tables.py -- do not edit by hand
\\begin{{table}}[H]
\\centering
\\begin{{tabular}}{{@{{}}lrr@{{}}}}
\\toprule
Quantity ({len(backtest)} h window) & Day-ahead forecast & Uncontrolled baseline \\\\
\\midrule
Total energy & {predicted.sum() / 1e3:.2f}\\,MWh & {baseline['predicted_demand_kwh'].sum() / 1e3:.2f}\\,MWh (realised {actual.sum() / 1e3:.2f}\\,MWh) \\\\
Peak hour & {predicted.max():.1f}\\,kWh & \\textbf{{{baseline['predicted_demand_kwh'].max():.1f}}}\\,kWh \\\\
Mean load & {predicted.mean():.1f}\\,kWh/h & {baseline['predicted_demand_kwh'].mean():.1f}\\,kWh/h \\\\
Energy bias against realised demand & ${bias * 100:+.1f}\\%$ & ${conserved * 100:+.2f}\\%$ \\\\
90\\% interval, mean width & {(upper - lower).mean():.1f}\\,kWh & not modelled \\\\
\\bottomrule
\\end{{tabular}}
\\caption{{Boulder: the two contract deliverables over the same window. The uncontrolled profile moves every session to an 18:00 local start at its own recorded power, so energy is conserved and only its timing changes.}}
\\label{{tab:baseline}}
\\end{{table}}
"""
    return tex, {
        "window_hours": len(backtest),
        "forecast_mwh": float(predicted.sum() / 1e3),
        "baseline_mwh": float(baseline["predicted_demand_kwh"].sum() / 1e3),
        "actual_mwh": float(actual.sum() / 1e3),
        "forecast_peak_kwh": float(predicted.max()),
        "baseline_peak_kwh": float(baseline["predicted_demand_kwh"].max()),
        "amplification": amplification,
        "bias_pct": bias * 100,
        "conserved_pct": conserved * 100,
        "interval_width_kwh": float((upper - lower).mean()),
        "coverage_pct": coverage,
    }


def macro_block(boulder: dict, palo_alto: dict, baseline: dict) -> str:
    """Return the LaTeX macro definitions quoted in the report prose."""
    entries = {
        "BoulderOrigins": boulder["origins"],
        "BoulderIntervals": boulder["intervals"],
        "BoulderBest": boulder["best_model"],
        "BoulderWape": f"{boulder['best_wape']:.3f}",
        "BoulderRtwo": f"{boulder['best_r2']:.3f}",
        "BoulderNaiveWape": f"{boulder['naive_daily_wape']:.3f}",
        "BoulderImprovement": f"{boulder['improvement_pct']:.0f}",
        "PaloAltoOrigins": palo_alto["origins"],
        "PaloAltoIntervals": palo_alto["intervals"],
        "PaloAltoWape": f"{palo_alto['best_wape']:.3f}",
        "PaloAltoNaiveWape": f"{palo_alto['naive_daily_wape']:.3f}",
        "PaloAltoImprovement": f"{palo_alto['improvement_pct']:.0f}",
        "WindowHours": baseline["window_hours"],
        "ForecastPeak": f"{baseline['forecast_peak_kwh']:.1f}",
        "BaselinePeak": f"{baseline['baseline_peak_kwh']:.1f}",
        "PeakAmplification": f"{baseline['amplification']:.1f}",
        "BiasPct": f"{baseline['bias_pct']:+.1f}",
        "ConservedPct": f"{baseline['conserved_pct']:+.2f}",
        "CoveragePct": f"{baseline['coverage_pct']:.1f}",
        "ForecastMwh": f"{baseline['forecast_mwh']:.2f}",
        "BaselineMwh": f"{baseline['baseline_mwh']:.2f}",
        "ActualMwh": f"{baseline['actual_mwh']:.2f}",
        "IntervalWidth": f"{baseline['interval_width_kwh']:.1f}",
        "BoulderGwh": f"{boulder['total_gwh']:.3f}",
        "BoulderPeakHour": f"{boulder['peak_hour']:02d}:00",
        "BoulderPeakShare": f"{boulder['peak_share_pct']:.1f}",
        "BoulderTroughHour": f"{boulder['trough_hour']:02d}:00",
        "BoulderTroughShare": f"{boulder['trough_share_pct']:.2f}",
        "BoulderRatio": f"{boulder['peak_to_trough']:.1f}",
        "PaloAltoGwh": f"{palo_alto['total_gwh']:.3f}",
        "PaloAltoPeakHour": f"{palo_alto['peak_hour']:02d}:00",
        "PaloAltoPeakShare": f"{palo_alto['peak_share_pct']:.1f}",
        "PaloAltoTroughHour": f"{palo_alto['trough_hour']:02d}:00",
        "PaloAltoTroughShare": f"{palo_alto['trough_share_pct']:.2f}",
        "PaloAltoRatio": f"{palo_alto['peak_to_trough']:.1f}",
    }
    lines = ["% generated by scripts/make_report_tables.py -- do not edit by hand"]
    lines += [f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in entries.items()]
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write every fragment the report includes."""
    settings = sp1_settings(root=repo_root())
    interim, processed = settings.interim_dir, settings.processed_dir
    out_dir = repo_root() / "docs" / "phase1-report" / "tables"
    out_dir.mkdir(parents=True, exist_ok=True)

    results, numbers = {}, {}
    for key in DATASETS:
        tex, nums = results_table(key, interim)
        (out_dir / f"results-{key}.tex").write_text(tex, encoding="utf-8")
        results[key] = tex
        numbers[key] = nums
        print(f"  wrote results-{key}.tex  (best {nums['best_model']}, WAPE {nums['best_wape']:.4f})")

    baseline_tex, baseline = baseline_table(interim, processed)
    (out_dir / "baseline.tex").write_text(baseline_tex, encoding="utf-8")
    print(f"  wrote baseline.tex        (peak amplification {baseline['amplification']:.2f}x)")

    for key in DATASETS:
        numbers[key].update(pattern_numbers(key, interim))
        print(
            f"  {key}: peak {numbers[key]['peak_hour']:02d}:00 ({numbers[key]['peak_share_pct']:.1f}%), "
            f"trough {numbers[key]['trough_hour']:02d}:00 ({numbers[key]['trough_share_pct']:.2f}%), "
            f"ratio {numbers[key]['peak_to_trough']:.1f}x, total {numbers[key]['total_gwh']:.3f} GWh"
        )

    (out_dir / "keynumbers.tex").write_text(
        macro_block(numbers["boulder"], numbers["palo-alto"], baseline), encoding="utf-8"
    )
    print("  wrote keynumbers.tex")
    return 0


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:  # pragma: no cover
        pass
    raise SystemExit(main())
