#!/usr/bin/env python
"""Command-line entry point for the SP1 pipeline.

Examples
--------
List the datasets described in ``config/datasets.yaml``::

    python subprojects/sp1-data-forecasting/scripts/run_sp1.py --list-datasets

Run on a configured dataset::

    python subprojects/sp1-data-forecasting/scripts/run_sp1.py --dataset ev-charging-cn

Run on the labelled synthetic fallback (unblocks SP2 while data is sourced)::

    python subprojects/sp1-data-forecasting/scripts/run_sp1.py --synthetic --days 120

Check the pipeline without running the slowest models::

    python subprojects/sp1-data-forecasting/scripts/run_sp1.py --synthetic \
        --models naive_daily,ridge --forecast-days 7
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Make ``src/`` importable without installing the package (see CONTRIBUTING.md:
# runs from a clean checkout).
SRC_DIR = Path(__file__).resolve().parents[1] / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from sp1.config import load_config, repo_root, sp1_settings
from sp1.contract import ContractError
from sp1.hourly import complete_grid
from sp1.ingest import (
    DatasetSpec,
    load_dataset,
    load_dataset_specs,
)
from sp1.pipeline import run_pipeline
from sp1.synthetic import (
    SyntheticSettings,
    calibration_report,
    generate_sessions,
)

DATASETS_YAML = "subprojects/sp1-data-forecasting/config/datasets.yaml"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="SP1 — build the 1-hour demand series and day-ahead demand forecast.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--dataset", help="key from config/datasets.yaml")
    source.add_argument(
        "--synthetic",
        action="store_true",
        help="use the labelled synthetic fallback (never presented as measured data)",
    )
    source.add_argument("--list-datasets", action="store_true", help="list known datasets and exit")

    parser.add_argument("--raw-file", help="raw CSV for an ad-hoc dataset")
    parser.add_argument(
        "--column-map",
        help='JSON mapping canonical->raw column names, e.g. \'{"start":"created_at","energy_kwh":"kwh"}\'',
    )
    parser.add_argument(
        "--kind", choices=("sessions", "hourly_load"), default="sessions",
        help="ad-hoc dataset shape (default: sessions)",
    )
    parser.add_argument("--timezone", default="Asia/Shanghai", help="timezone of the raw timestamps")
    parser.add_argument(
        "--default-power-kw", type=float, default=None,
        help="charger power assumed when a session has energy but no end time",
    )

    parser.add_argument("--models", help="comma-separated model names (default: all)")
    parser.add_argument("--horizon", type=int, default=None, help="forecast horizon in hours")
    parser.add_argument("--forecast-days", type=int, default=None, help="output window in days")
    parser.add_argument("--source-label", default=None, help="override the provenance string")
    parser.add_argument("--no-interim", action="store_true", help="skip data/interim outputs")

    parser.add_argument("--evs", type=int, default=200, help="synthetic: number of vehicles")
    parser.add_argument("--days", type=int, default=120, help="synthetic: number of days")
    parser.add_argument("--seed", type=int, default=42, help="synthetic: random seed")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run the requested pipeline and print a JSON summary."""
    _force_utf8_stdout()
    args = parse_args(argv)
    root = repo_root()
    config = load_config(root)
    settings = sp1_settings(config, root)
    specs = load_dataset_specs(root / DATASETS_YAML)

    if args.list_datasets:
        print(json.dumps(_describe_specs(specs), indent=2, ensure_ascii=False))
        return 0

    model_names = [m.strip() for m in args.models.split(",")] if args.models else None

    if args.synthetic:
        synthetic_settings = SyntheticSettings(n_evs=args.evs, days=args.days)
        sessions = generate_sessions(synthetic_settings, seed=args.seed)
        report = calibration_report(sessions, synthetic_settings)
        result = run_pipeline(
            settings,
            sessions=sessions,
            source_label=(
                "SYNTHETIC — calibrated profile generated by sp1.synthetic "
                f"(seed={args.seed}, {args.evs} EVs, {args.days} days); NOT measured data"
            ),
            synthetic=True,
            provenance={"calibration": report},
            model_names=model_names,
            horizon=args.horizon,
            forecast_days=args.forecast_days,
            write_interim=not args.no_interim,
        )
        print(json.dumps({**result.summary, "calibration": report}, indent=2, ensure_ascii=False))
        return 0

    spec = _resolve_spec(args, specs, settings)
    table = load_dataset(spec)
    if spec.kind == "sessions":
        result = run_pipeline(
            settings,
            sessions=table,
            source_label=_source_label(spec, args),
            provenance=_provenance(spec),
            model_names=model_names,
            horizon=args.horizon,
            forecast_days=args.forecast_days,
            write_interim=not args.no_interim,
        )
        summary = {**result.summary, "n_sessions": len(table)}
    else:
        result = run_pipeline(
            settings,
            hourly_load=complete_grid(table.assign(session_count=0)),
            source_label=_source_label(spec, args),
            provenance=_provenance(spec),
            model_names=model_names,
            horizon=args.horizon,
            forecast_days=args.forecast_days,
            write_interim=not args.no_interim,
        )
        summary = {**result.summary, "n_intervals": len(table)}

    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


def _resolve_spec(args: argparse.Namespace, specs: dict, settings) -> DatasetSpec:
    if args.dataset:
        if args.dataset not in specs:
            raise ContractError(
                f"dataset '{args.dataset}' is not in {DATASETS_YAML}; known: {sorted(specs)}"
            )
        return specs[args.dataset]
    if not args.raw_file or not args.column_map:
        raise ContractError("--raw-file and --column-map are required together")
    return DatasetSpec(
        key="ad-hoc",
        kind=args.kind,
        path=Path(args.raw_file),
        timezone=args.timezone,
        column_map=json.loads(args.column_map),
        default_power_kw=args.default_power_kw,
        description="ad-hoc dataset passed on the command line",
    )


def _source_label(spec: DatasetSpec, args: argparse.Namespace) -> str:
    if args.source_label:
        return args.source_label
    parts = [spec.description or spec.key]
    if spec.url:
        parts.append(spec.url)
    if spec.licence:
        parts.append(f"licence: {spec.licence}")
    return " — ".join(parts)


def _provenance(spec: DatasetSpec) -> dict:
    payload = {}
    for key in ("licence", "url", "description"):
        value = getattr(spec, key, "")
        if value:
            payload[key] = value
    if spec.path is not None:
        payload["raw_file"] = spec.path.name
    return payload


def _describe_specs(specs: dict) -> dict:
    return {
        key: {
            "kind": spec.kind,
            "raw_file": (
                [str(path) for path in spec.paths]
                if spec.paths
                else (str(spec.path) if spec.path else None)
            ),
            "present": all(
                path.is_file() for path in (spec.paths or ([spec.path] if spec.path else []))
            ),
            "description": spec.description,
            "licence": spec.licence,
            "url": spec.url,
            "column_map": spec.column_map,
        }
        for key, spec in specs.items()
    }


def _force_utf8_stdout() -> None:
    """Avoid UnicodeEncodeError when the console is GBK (see the workspace pitfall log)."""
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:  # pragma: no cover - Python < 3.7
        pass


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ContractError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(2) from error
